In [ ]:
import numpy as np

Function to check if matrix is symmetric or not-

In [ ]:
def isSymmetric(M):
    N, _ = np.shape(M)
    for i in range(N):
        for j in range(N):
            if (M[i][j] != M[j][i]):
                return False
    return True

Function to check if matrix is positive definite or not-

In [ ]:
def check_positive_definite(M):
  eigen_val = np.linalg.eigvals(M)
  #print(eigen_val)
  #print("\n")

  positive_all = True
  for i in eigen_val:
    if i < 0:
      positive_all = False
      break
    else:
      positive_all = True

  if(positive_all):
    return True
  return False

Function to decompose matrix into cholesky form A = LL^t
- It returns the lower triangular matrix L

In [ ]:
def cholesky(a):
    a = np.array(a, float)
    L = np.zeros_like(a)
    n,_= np.shape(a)
    for j in range(n): 
        for i in range(j,n):
            if i == j:
                sumk = 0 
                for k in range(j):
                    sumk += L[i,k] **2
                L[i,j] = np.sqrt(a[i,j]-sumk)
            else:
                sumk = 0
                for k in range(j):
                    sumk+= L[i,k]*L[j,k]
                L[i,j] = (a[i,j] - sumk) / L[j,j]
    return L

Function to solve the linear system of equations-
- It takes lower triangular matrix 'L', upper triangular matrix 'U' and matrix 'b' as input parameters.
- It returns the output matrix 'X'

In [ ]:
def solveLU(L,U,b):
  L = np.array(L,float)
  U = np.array(U,float)
  b = np.array(b,float)
  n,_ = np.shape(L)
  y = np.zeros(n)
  x = np.zeros(n)

  # forward substitution
  for i in range(n):
    sumj = 0
    for j in range(i):
      sumj += L[i,j] * y[j]
    y[i] = (b[i]-sumj)/L[i,i]

  # backward substitution
  for i in range(n-1, -1, -1):
    sumj = 0
    for j in range(i+1, n):
      sumj += U[i,j] * x[j]
    x[i] = (y[i]-sumj)/U[i,i]
    
  return x

Sample code to test above mentioned functions-

In [ ]:
'''M = [[5.2,3,0.5,1,2], 
      [3,6.3,-2,4,0], 
      [0.5,-2,8,-3.1,3], 
     [1,4,-3.1,7.6,2.6], 
      [2,0,3,2.6,15]]'''

'''A = [[8.00, 3.22, 0.8, 0.00, 4.10],
     [3.22, 7.76, 2.33, 1.91, -1.03],
     [0.8, 2.33, 5.25, 1.00, 3.02],
     [0.00, -1.91, 1.00, 7.50, 1.03],
     [4.10, -1.03, 3.02, 1.03, 6.44]]

b = [9.45, -12.20, 7.78, -8.1, 10.0]'''

A = [  [21, -9, 0, -7],
       [-9, 15, -4, -2],
       [0, -4, 19, -8],
       [-7,-2,-8,29]
     ]

b = [19, -11, 8, 0]

'''A = [[1,2,3],
     [2,8,22],
     [3,22,82]]

b = [5,6,-10]'''

print("Given matrix A-\n")
print(np.matrix(A))

is_symmetric = isSymmetric(A)
print("Is symmetric matrix- ",is_symmetric )
is_positive_definite = check_positive_definite(A)
print("Is positive definite matrix- ",is_positive_definite )
print("\n")

if(is_symmetric and is_positive_definite):
  L = cholesky(A)

  print("Matrix L is-\n")
  print(np.matrix(L))


  #to verify if cholesky decomposition is correct or not
  M = np.dot(L, np.transpose(L))
  print("\nMatrix A = LL^T is-\n")
  print(np.matrix(M))

  x = solveLU(L, np.transpose(L), b)
  print("\nResult vector X is-")
  print(x)

else:
  print("Cholesky Decomposition not possible")
Y = np.linalg.solve(A,b)
print("To verify-")
print(Y)

Given matrix A-

[[21 -9  0 -7]
 [-9 15 -4 -2]
 [ 0 -4 19 -8]
 [-7 -2 -8 29]]
Is symmetric matrix-  True
Is positive definite matrix-  True


Matrix L is-

[[ 4.58257569  0.          0.          0.        ]
 [-1.96396101  3.33809184  0.          0.        ]
 [ 0.         -1.19828938  4.19095485  0.        ]
 [-1.52752523 -1.49786172 -2.33714563  4.3544032 ]]

Matrix A = LL^T is-

[[21. -9.  0. -7.]
 [-9. 15. -4. -2.]
 [ 0. -4. 19. -8.]
 [-7. -2. -8. 29.]]

Result vector X is-
[1.14427235 0.19211077 0.6600367  0.47153178]
To verify-
[1.14427235 0.19211077 0.6600367  0.47153178]
